### PR TITLE
Fix InMemory Repository

### PR DESCRIPTION
**Pull request by ahmedig**
Fixed the InMemory Repository, and wrote tests to verify the fix.

### CODE REVIEW

**Comment by ahmedig** [comment]
Aren't you going to review and merge? :) @rbanks54

**Comment by rbanks54** [comment]
There was a little period known as Christmas and family holidays that got in the way :-)

**Comment by ahmedig** [comment]
Yeah sure :) that was just a reminder; no hurry.

**Comment by rbanks54** [comment]
Why upgrade newtonsoft library? Was there something specific you needed from it.
I ask because you've effectively got two changes in the one pull request. One for the package version, and on for the actual code fix. PRs are much simpler to review if they only contain changes for one item at a time.

**Comment by rbanks54** [comment]
Closing this as per plans relating to internal framework changes  (see #11 )

**Pull request closed without merging**
